name: build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'README.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: 'npm'
    - run: npm ci
    - run: npm run pdf
    - run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add README.pdf
        git commit -m "generated README.pdf"
        echo "PULL_MERGE_BRANCH=${GITHUB_REF#refs/}"
        git push origin $PULL_MERGE_BRANCH
